/**
 * Zod schemas for Stage 3: App Generation output.
 * @NEURON owns this file.
 *
 * Defines the shape Claude Sonnet must produce via tool_use.
 * Phase A: 6 components (form_field, data_table, kpi_card, bar_chart, filter_bar, container).
 * Max 20 components per app.
 */

import { z } from 'zod';

/** Phase A allowed component types */
export const PHASE_A_COMPONENT_TYPES = [
  'form_field',
  'data_table',
  'kpi_card',
  'bar_chart',
  'filter_bar',
  'container',
] as const;

export const phaseAComponentTypeSchema = z.enum(PHASE_A_COMPONENT_TYPES);

/** Aggregate transforms for data bindings */
export const AGGREGATE_TRANSFORMS = [
  'count',
  'sum',
  'avg',
  'min',
  'max',
  'distinct',
  'latest',
  'first',
] as const;

export const aggregateTransformSchema = z.enum(AGGREGATE_TRANSFORMS);

/** Position within the CSS Grid layout */
export const positionSchema = z.object({
  row: z.number().int().nonnegative(),
  col: z.number().int().nonnegative(),
  span: z.number().int().min(1).max(4).optional(),
});

/** A single component instance as generated by Claude */
export const generatedComponentSchema = z.object({
  id: z.string().min(1).max(64),
  type: phaseAComponentTypeSchema,
  props: z.record(z.unknown()),
  position: positionSchema,
  dataBinding: z.string().optional(),
});

export type GeneratedComponent = z.infer<typeof generatedComponentSchema>;

/** Layout config for the generated app */
export const generatedLayoutSchema = z.object({
  type: z.enum(['single_page', 'multi_page', 'sidebar']),
  columns: z.number().int().min(1).max(4).optional(),
  gap: z.string().optional(),
});

/** Data binding with optional transform */
export const generatedDataBindingSchema = z.object({
  id: z.string().min(1).max(64),
  sourceId: z.string().min(1),
  field: z.string().min(1),
  transform: z.string().optional(),
});

export type GeneratedDataBinding = z.infer<typeof generatedDataBindingSchema>;

/** The complete app schema as returned by Claude's create_app tool */
export const generatedAppSchema = z.object({
  name: z.string().min(1).max(200),
  archetype: z.enum([
    'crud_form', 'dashboard', 'tracker', 'report',
    'approval', 'checklist', 'gallery', 'multi_view',
  ]),
  layout: generatedLayoutSchema,
  components: z.array(generatedComponentSchema).min(1).max(20),
  dataBindings: z.array(generatedDataBindingSchema).max(50),
});

export type GeneratedAppSchema = z.infer<typeof generatedAppSchema>;

/**
 * Branded type — only schemas that pass all 3 validation passes
 * can be cast to ValidatedAppSchema. This ensures type-level safety
 * so only validated schemas reach the renderer/DB.
 */
export type ValidatedAppSchema = GeneratedAppSchema & { readonly __validated: true };

/** Mark a schema as validated (only called from 04-validate.ts) */
export function brandAsValidated(schema: GeneratedAppSchema): ValidatedAppSchema {
  return schema as ValidatedAppSchema;
}
